### ISSUE TITLE
Bug checking for `document`

### ISSUE THREAD

**Issue by marcalj** [orizens/angular2-infinite-scroll#18] opened 2016-06-05 18:05 UTC
https://github.com/orizens/angular2-infinite-scroll/blob/master/src/scroller.ts#L26
```window.hasOwnProperty('document')``` is false!

Maybe use ```!!window.document```

See this issue: https://github.com/angular/angular/issues/9030

**Comment by apavillet** [comment] 2016-06-09 10:36
More on this : 

Scroll was not working on window for ie11 because `this.isContainerWindow = this.windowElement.hasOwnProperty('document');` returns false on this browser.
It's working fine on other browser.

`!!window.document` does not seem to work

As a workaround I added the `scrollWindow` parameter in the scroller.ts constructor from InfiniteScroll.ts, only testing if it's true or not.

`this.isContainerWindow = this.scrollWindow;`

This allow not to rely on browser for detection, I do not know if it's optimal.

**Comment by ahall** [comment] 2016-06-15 23:59
Thanks for this, I just changed the line in the constructor to:

```
// HACK: To make it work on IE 11, the browser detection does not work at all.
this.isContainerWindow = true;
```

This works fine now in IE and all browsers I have tried. BTW also noticed that if immediateCheck is not set to true, the browser hogs 20% CPU on my computer before I do any scrolling, then after I start scrolling it sorts itself. Definitely recommend having immediateCheck set to true!

**Comment by apavillet** [comment] 2016-06-16 08:43
@ahall Your solution would not work if you need the infinite scroll outside of a window (  `[scrollWindow]="false"` )

If you need both you can modify scroller.ts like this, adding a parameter  scrollWindow in the constructor

`constructor(
		private windowElement: Window | ElementRef | any,
		private scrollWindow: boolean,
		private $interval: Function,
		private $elementRef: ElementRef,
		private infiniteScrollCallback: Function,
		infiniteScrollDistance: number,
		infiniteScrollParent: Window | ElementRef | any,
		private infiniteScrollThrottle: number,
		private isImmediate: boolean
		) {
		this.isContainerWindow = this.scrollWindow;
		this.documentElement = this.isContainerWindow ? this.windowElement.document.documentElement : null;`

and pass if from infinite-scroll.ts

`ngOnInit() {
    const containerElement = this.scrollWindow ? window : this.element;
    this.scroller = new Scroller(containerElement, this.scrollWindow, setInterval, this.element, this.onScroll.bind(this), this._distance, {}
        , this._throttle, this._immediate);
  }`

Thanks for the tip on immediate check

**Comment by orizens** [comment] 2016-06-16 09:15
@apavillet ,
currently, this line on scroller.ts, 
```
this.documentElement = this.isContainerWindow ? this.windowElement.document.documentElement : null;
```
also relies on the 'document' property, so, your solution may not work when scrollWindow is true. 
is there any other property that we can rely on to differentiate window and other dom element?

**Comment by apavillet** [comment] 2016-06-16 09:26
@orizens I tried to find one but it might be hard, because of inconsistency between browsers, versions and such.

I think it works since the only problem is `this.windowElement.hasOwnProperty('document');` on IE which is always false

Getting the windowElement.document.documentElement is not a problem as far as I can see

**Comment by orizens** [comment] 2016-06-16 09:39
hi @apavillet @marcalj @ahall 
I just pushed an attempt to fix this issue.
notice - this is a duplicated issue with #21 
please let me know if that fixes the issue.

**Comment by ahall** [comment] 2016-06-16 10:26
Confirmed as working on IE 11, Chrome and Safari.

Any idea why infinite scroll takes up constant 20% CPU before the handler gets called?

**Comment by orizens** [comment] 2016-06-16 10:53
@ahall Thanks for the confirmation. I'm closing this issue. 
20% cpu - not sure that it originates in the scroller, however, it could be the interval.

**Closed by orizens** 2016-06-16 10:53 UTC
Labels: to-verify

**Comment by ahall** [comment] 2016-06-16 11:33
Thanks. Should I raise a separate issue for the constant 20% CPU utilisation until the handler is called initially?

**Comment by orizens** [comment] 2016-06-16 11:37
see if you can provide proper steps to reproduce it with other browsers as well, while taking out other variables.

**Comment by ahall** [comment] 2016-06-16 11:44
My page utilises 20% CPU constantly until I scroll includes this piece of code:

```
<div class="infinite-scroll" infinite-scroll [infiniteScrollDistance]="2" [immediateCheck]="false" (scrolled)="onScrollDown()">
```

After modifying the code to this it no longer does:

```
<div class="infinite-scroll" infinite-scroll [infiniteScrollDistance]="2" [immediateCheck]="true" (scrolled)="onScrollDown()">
```

I am using OSX 10.11.5 with Chrome Version 50.0.2661.102 (64-bit)
I have tried Safari 9 and IE 11 on Windows with similar results.

Looks once the scroll handler() function gets called the first time the problem goes away. Thats why immediateCheck set to true seems to fix the problem.

**Comment by orizens** [comment] 2016-06-16 12:14
well - that sounds strange. 
the solution is clear - however, not always needed in terms of functionality.

**Comment by marcalj** [comment] 2016-06-16 15:11
I cannot check because cannot use the plugin now :( #30

**Comment by marcalj** [comment] 2016-06-16 15:23
It's working on the console, so I expect it's working now. Can't check due to #28.
